{{- if and .Values.storegateway.enabled .Values.storegateway.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-storegateway" (include "thanos.fullname" .)) .Values.storegateway.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: storegateway
  {{- with .Values.storegateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
