{{- if .Values.query.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.fullname" . }}-query
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
    prometheus-operator/monitor: "true"
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "thanos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: query
{{- end }}
