apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thanos.fullname" . }}-objstore-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
type: Opaque
stringData:
  objstore.yml: |
    {{- include "thanos.objstoreConfig" . | nindent 4 }}
