## ClusterRole: rabbitmq-cluster-operator-role
## Source: upstream cluster-operator.yml (v2.19.1)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "rabbitmq-cluster-operator.labels" . | nindent 4 }}
  name: rabbitmq-cluster-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters/status
  verbs:
  - get
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - update
  - watch

---
## ClusterRole: rabbitmq-cluster-service-binding-role
## Source: upstream cluster-operator.yml (v2.19.1)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "rabbitmq-cluster-operator.labels" . | nindent 4 }}
    servicebinding.io/controller: "true"
  name: rabbitmq-cluster-service-binding-role
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - get
  - list
  - watch

