## ServiceAccount: rabbitmq-cluster-operator
## Source: upstream cluster-operator.yml (v2.19.1)
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "rabbitmq-cluster-operator.labels" . | nindent 4 }}
  name: rabbitmq-cluster-operator
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

