{{- if .Values.queryFrontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.fullname" . }}-query-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: query-frontend
spec:
  replicas: {{ .Values.queryFrontend.replicaCount }}
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "thanos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: query-frontend
  template:
    metadata:
      labels:
        {{- include "thanos.labels" . | nindent 8 }}
        app.kubernetes.io/component: query-frontend
    spec:
      serviceAccountName: {{ default (printf "%s-query-frontend" (include "thanos.fullname" .)) .Values.queryFrontend.serviceAccount.name }}
      automountServiceAccountToken: true
      securityContext:
        {{- include "thanos.podSecurityContext" . | nindent 8 }}
      containers:
        - name: query-frontend
          image: {{ include "thanos.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- include "thanos.containerSecurityContext" . | nindent 12 }}
          args:
            - query-frontend
            - --log.level={{ .Values.queryFrontend.logLevel }}
            - --log.format={{ .Values.queryFrontend.logFormat }}
            - --http-address=0.0.0.0:10902
            - --query-frontend.downstream-url=http://{{ include "thanos.fullname" . }}-query.{{ .Release.Namespace }}.svc.cluster.local:9090
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
            httpGet:
              path: /-/ready
              port: http
              scheme: HTTP
          {{- with .Values.queryFrontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
