{{- if and .Values.bucketweb.enabled .Values.bucketweb.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-bucketweb" (include "thanos.fullname" .)) .Values.bucketweb.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: bucketweb
  {{- with .Values.bucketweb.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
