{{- /*
Keycloak External Database Secret
*/}}
{{- if not .Values.externalDatabase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-externaldb" .Release.Name }}
  namespace: {{ include "keycloak.namespace" . | quote }}
  labels: {{- include "keycloak.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $secretName := printf "%s-externaldb" .Release.Name }}
  {{- $secret := lookup "v1" "Secret" (include "keycloak.namespace" .) $secretName }}
  {{- if and $secret (index $secret.data "db-password") }}
  db-password: {{ index $secret.data "db-password" }}
  {{- else if .Values.externalDatabase.password }}
  db-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- else }}
  db-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}
