{{- /*
Keycloak Admin Password Secret
*/}}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ include "keycloak.namespace" . | quote }}
  labels: {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $secretName := include "keycloak.fullname" . }}
  {{- $secret := lookup "v1" "Secret" (include "keycloak.namespace" .) $secretName }}
  {{- if and $secret (index $secret.data "admin-password") }}
  admin-password: {{ index $secret.data "admin-password" }}
  {{- else if .Values.auth.adminPassword }}
  admin-password: {{ .Values.auth.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}
